development: &development
  bucket: changeons-bucket-dev
  access_key_id: AKIAINEIFXACIJ6YXYQQ
  secret_access_key: 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
staging:
  <<: *development
  bucket: changeons-bucket-staging

production:
  <<: *development
  bucket: changeons-bucket-pro