development:
  bucket: changeons-bucket-dev
  access_key_id: AKIAINEIFXACIJ6YXYQQ
  secret_access_key: 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
staging:
  bucket: changeons-bucket-staging
  access_key_id: AKIAINEIFXACIJ6YXYQQ
  secret_access_key: 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
production:
  bucket: changeons-bucket-pro
  access_key_id: AKIAINEIFXACIJ6YXYQQ
  secret_access_key: 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